version: 1.0
workflows:
   - name: UWGAC-GENESIS-VCF-to-GDS
     subclass: CWL
     publish: True
     primaryDescriptorPath: /vcftogds/vcf-to-gds-wf.cwl
   - name: UWGAC-GENESIS-Single-Variant-Association-Workflow
     subclass: CWL
     primaryDescriptorPath: /single-variant-association/single-variant-association-wf.cwl
