name: sva

on: [push]

jobs:
  test-define_segments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache docker
      uses: actions/cache@v1
      env:
        cache-name: cache-docker-image
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cwltool
    - name: Test with cwltool
      run: |
        cd single-variant-association
        cwltool --outdir exec define_segments_r.cwl 
        cwltool --outdir exec filter_segments.cwl job-filter_segments.yml

  test-assoc_single:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache docker
      uses: actions/cache@v1
      env:
        cache-name: cache-docker-image
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cwltool
    - name: Test with cwltool
      run: |
        cd single-variant-association
        cwltool --outdir exec assoc_single_r.cwl job-assoc_single_r.yml
        if cwltool --outdir exec assoc_single_r.cwl job-assoc_single_r2.yml ; then
          exit 1
        fi

  test-assoc_combine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache docker
      uses: actions/cache@v1
      env:
        cache-name: cache-docker-image
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cwltool
    - name: Test with cwltool
      run: |
        cd single-variant-association
        cwltool --outdir exec assoc_combine_r.cwl job-assoc_combine_r.yml
